name: concurrency demo

on:
  push:
    

jobs:
  concurrency-job:
    runs-on: ubuntu-latest
    concurrency:
      group: 'concurrency-demo-group'
      cancel-in-progress: false
    steps:
      - name: Wait for 10 seconds
        run: sleep 10
 