name: if condition demo

on:
  push:


jobs:  
   if-condition-job:
    runs-on: ubuntu-latest

    steps:
      - name: fail
        run: exit 1

      - name: This step runs only if the previous step failed
        if: failure()
        run: echo "The previous step has failed."

      - name: This step runs only if the previous step succeeded
        if: success()
        run: echo "The previous step was successful."

      - name : This step runs always
        if: always()
        run: echo "This step runs regardless of the previous step's outcome." 